{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pgadmin.pvcName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
    {{- with .Values.persistence.labels }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- $storageClass := default .Values.global.storageClass .Values.persistence.storageClass }}
  {{- if $storageClass }}
  storageClassName: {{ if eq "-" $storageClass }}""{{ else }}{{ $storageClass | quote }}{{ end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
