annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Pin the default image to wodby/vinyl:6.0-r0
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
dependencies:
- name: common
  repository: oci://registry-1.docker.io/wodby
  version: 1.x.x
name: vinyl
version: 0.2.3
