apiVersion: v2
name: frps
description: A Helm chart for the FRP reverse proxy server
type: application
version: 0.1.0
appVersion: "0.69.1"
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Add the initial FRPS server deployment with token authentication and HTTP proxying
dependencies:
- name: common
  repository: oci://registry-1.docker.io/wodby
  version: 1.x.x
