apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mtproxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mtproxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.updateStrategy }}
  strategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mtproxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mtproxy.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "mtproxy.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "mtproxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: mtproxy
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "mtproxy.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "mtproxy.secretName" . }}
                  key: secret
                  optional: false
            - name: WORKERS
              value: {{ .Values.config.workers | quote }}
            {{- if .Values.config.debug }}
            - name: DEBUG
              value: "1"
            {{- end }}
            {{- if or .Values.config.tag .Values.existingSecret }}
            - name: TAG
              valueFrom:
                secretKeyRef:
                  name: {{ include "mtproxy.secretName" . }}
                  key: tag
                  optional: true
            {{- end }}
            {{- with .Values.envVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: proxy
              containerPort: 443
              protocol: TCP
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
