{{- if eq (include "mtproxy.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mtproxy.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mtproxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.secrets }}
  secret: {{ join "," .Values.config.secrets | quote }}
  {{- end }}
  {{- if .Values.config.tag }}
  tag: {{ .Values.config.tag | quote }}
  {{- end }}
{{- end }}
