{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frps.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frps.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  auth-token: {{ .Values.auth.token | quote }}
  web-server-password: {{ .Values.webServer.password | quote }}
{{- end }}
