apiVersion: v1
kind: Service
metadata:
  name: {{ include "frps.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frps.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: control
      port: {{ .Values.service.ports.control }}
      targetPort: control
      protocol: TCP
    - name: proxy-http
      port: {{ .Values.service.ports.proxyHttp }}
      targetPort: proxy-http
      protocol: TCP
    - name: dashboard
      port: {{ .Values.service.ports.dashboard }}
      targetPort: dashboard
      protocol: TCP
  selector:
    {{- include "frps.selectorLabels" . | nindent 4 }}
