apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opensmtpd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opensmtpd.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "opensmtpd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "opensmtpd.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "opensmtpd.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "opensmtpd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: opensmtpd
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "opensmtpd.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.args "context" $) | nindent 12 }}
          {{- end }}
          {{- with .Values.envVars }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: smtp
              containerPort: 25
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - make
              - check-ready
              - -f
              - /usr/local/bin/actions.mk
            initialDelaySeconds: 80
            failureThreshold: 2
            timeoutSeconds: 3
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
              - make
              - check-ready
              - -f
              - /usr/local/bin/actions.mk
            initialDelaySeconds: 5
            failureThreshold: 2
            timeoutSeconds: 3
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
