apiVersion: v1
kind: Service
metadata:
  name: {{ include "opensmtpd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opensmtpd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 25
      targetPort: smtp
      protocol: TCP
      name: smtp
  selector:
    {{- include "opensmtpd.selectorLabels" . | nindent 4 }}
