apiVersion: v2
name: memcached
description: Memcached chart for Wodby Memcached images.
type: application
version: 0.2.1
appVersion: "1.6.45"
keywords:
  - memcached
  - cache
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/wodby
    version: 1.x.x
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Pin the default image to wodby/memcached:1.6-r0
