apiVersion: v2
name: distribution
description: CNCF Distribution Registry chart for Wodby
type: application
version: 0.2.2
appVersion: "3.1.1"
keywords:
- registry
- oci
- distribution
dependencies:
- name: common
  repository: oci://registry-1.docker.io/wodby
  version: 1.x.x
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Drain active registry connections during pod termination
    - kind: changed
      description: Increase the default termination grace period to 60 seconds
