{{- if .Values.auth.token.rootCertBundle -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "distribution.fullname" . }}-token-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "distribution.labels" . | nindent 4 }}
type: Opaque
stringData:
  rootcertbundle.crt: |
    {{- .Values.auth.token.rootCertBundle | nindent 4 }}
{{- end }}
