apiVersion: v2
name: prometheus
description: Prometheus server chart for Wodby services
type: application
version: 0.2.2
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Pin the default image to wodby/prometheus:3.13-r0
appVersion: "3.13.3"
dependencies:
- name: common
  repository: oci://registry-1.docker.io/wodby
  version: 1.x.x
