apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mailpit.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mailpit.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mailpit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mailpit.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "mailpit.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "mailpit.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: mailpit
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "mailpit.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.args "context" $) | nindent 12 }}
          {{- end }}
          {{- with .Values.envVars }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: smtp
              containerPort: 1025
            - name: web
              containerPort: 8025
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
          - name: data
            mountPath: /data
      volumes:
      - name: empty-dir
        emptyDir: {}
        {{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
      - name: spool
        persistentVolumeClaim:
          claimName: {{ printf "%s" (tpl .Values.persistence.existingClaim .) }}
        {{- else if not .Values.persistence.enabled }}
      - name: data
        emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  