- name: PG_META_PORT
  value: '8080'
- name: PG_META_DB_HOST
  valueFrom:
    secretKeyRef:
      name: '{{ include "supabase.fullname" . }}-credentials'
      key: POSTGRES_HOST
- name: PG_META_DB_PORT
  valueFrom:
    secretKeyRef:
      name: '{{ include "supabase.fullname" . }}-credentials'
      key: POSTGRES_PORT
- name: PG_META_DB_NAME
  valueFrom:
    secretKeyRef:
      name: '{{ include "supabase.fullname" . }}-credentials'
      key: POSTGRES_DB
- name: PG_META_DB_USER
  value: postgres
- name: PG_META_DB_PASSWORD
  valueFrom:
    secretKeyRef:
      name: '{{ include "supabase.fullname" . }}-credentials'
      key: POSTGRES_PASSWORD
- name: CRYPTO_KEY
  valueFrom:
    secretKeyRef:
      name: '{{ include "supabase.fullname" . }}-credentials'
      key: PG_META_CRYPTO_KEY
