apiVersion: v2
name: gotenberg
version: 0.2.1
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Drain service endpoints before Gotenberg shuts down
    - kind: changed
      description: Increase the default termination grace period to 60 seconds
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/wodby
    version: 1.x.x
