apiVersion: v2
name: gotenberg
version: 0.2.2
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: Omit RollingUpdate settings when the Recreate deployment strategy is selected
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/wodby
    version: 1.x.x
