apiVersion: v2
name: rabbitmq
description: RabbitMQ chart for Wodby RabbitMQ images.
type: application
version: 0.2.1
appVersion: 4.3.2
keywords:
  - rabbitmq
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/wodby
    version: 1.x.x
