apiVersion: v2
name: rabbitmq
description: RabbitMQ chart for Wodby RabbitMQ images.
type: application
version: 0.3.2
appVersion: "4.3.6"
keywords:
  - rabbitmq
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/wodby
    version: 1.x.x
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Pin the default image to wodby/rabbitmq:4.3-r0
