name: frpc
apiVersion: v2
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Pin the default image to wodby/frp:0.69-r0
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/wodby
    version: 1.x.x
version: 0.3.2
