apiVersion: v1
kind: Service
metadata:
  name: {{ include "node.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- if .Values.containerPorts.node }}
    - port: 3000
      targetPort: node
      protocol: TCP
      name: node
  {{- end }}
  {{- if .Values.containerPorts.sshd }}
    - port: 22
      targetPort: sshd
      protocol: TCP
      name: sshd
  {{- end }}
  selector:
    {{- include "node.selectorLabels" . | nindent 4 }}
