apiVersion: v1
kind: Service
metadata:
  name: {{ include "go.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- if .Values.containerPorts.go }}
    - port: 8080
      targetPort: go
      protocol: TCP
      name: go
  {{- end }}
  {{- if .Values.containerPorts.sshd }}
    - port: 22
      targetPort: sshd
      protocol: TCP
      name: sshd
  {{- end }}
  selector:
    {{- include "go.selectorLabels" . | nindent 4 }}
