{{- if eq ( include "tailscale.createSecret" . ) "true" }}
{{- $password := .Values.authKey  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tailscale.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "tailscale.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.authKey }}
  TS_AUTHKEY: {{ required "A tailscale auth key is required!" $password | b64enc | quote }}
{{- end }}
{{- end }}
