apiVersion: v1
kind: Service
metadata:
  name: {{ include "tailscale.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tailscale.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: tailscale
      port: 80
      targetPort: 80
  selector:
    {{- include "tailscale.selectorLabels" . | nindent 4 }}
