annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Pin the default image to wodby/nginx:1.30-r0
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
dependencies:
- name: common
  repository: oci://registry-1.docker.io/wodby
  version: 1.x.x
name: nginx
version: 0.4.0
