apiVersion: v2
dependencies:
- name: common
  repository: oci://registry-1.docker.io/wodby
  version: 1.x.x
name: httpd
version: 0.3.1
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Drain service endpoints before Apache receives its graceful stop signal
