apiVersion: v2
name: tailscale
description: A Helm chart for Tailscale

type: application

version: 0.2.0
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Expose consistent StatefulSet update readiness and graceful shutdown settings
    - kind: changed
      description: Wait 10 seconds after readiness before continuing rolling updates
dependencies:
- name: common
  repository: oci://registry-1.docker.io/wodby
  version: 1.x.x
