annotations:
  licenses: Apache-2.0
apiVersion: v2
appVersion: 1.0.0
description: A Library Helm Chart for grouping common logic between wodby charts. This chart is not deployable by itself.
home: https://wodby.com
keywords:
  - common
  - helper
  - template
  - function
  - wodby
maintainers:
  - name: Wodby, Inc. All Rights Reserved.
    url: https://github.com/wodby/charts
name: common
sources:
  - https://github.com/wodby/charts/tree/main/common
type: library
version: 1.0.0
