{{- if eq (include "rabbitmq.createGeneratedSecret" .) "true" }}
{{- $secretName := include "rabbitmq.generatedSecretName" . }}
{{- $password := include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "password" "providedValues" (list "auth.password") "length" 24 "strong" false "honorProvidedValues" true "context" $) }}
{{- $cookie := include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "erlang-cookie" "providedValues" (list "auth.erlangCookie") "length" 32 "strong" false "honorProvidedValues" true "context" $) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if not .Values.auth.existingPasswordSecret }}
  password: {{ $password }}
  {{- end }}
  {{- if not .Values.auth.existingErlangSecret }}
  erlang-cookie: {{ $cookie }}
  {{- end }}
{{- end }}
