# Default values for wsp-client.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: wodby/wsp
  tag: 'client'
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ""

env:
  open:
    LOG_FORMAT: "TEXT"
    LOG_LEVEL: "DEBUG"

resources: {}
#  limits:
#    cpu: 600m
#    memory: 512Mi
#  requests:
#    cpu: 600m
#    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

annotations: {}

verticalAutoscaling:
  enabled: false
  minAllowed: 50m

podDisruptionBudget:
  enabled: false
  maxUnavailable: 1
