{{- if eq ( include "valkey.createSecret" . ) "true" }}
{{- $password := .Values.auth.password  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- if .Values.auth.password }}
  password: {{ required "A Valkey Password is required!" $password | b64enc | quote }}
{{- end }}  
{{- end }}
