{{- if not .Values.frpc.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frpc.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: frpc
{{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
{{- end }}
type: Opaque
data:
  FRPC_AUTH_OIDC_CLIENT_SECRET: {{ .Values.frpc.oidcClientSecret | b64enc | quote }}
  FRPC_HTTP_PASSWORD: {{ .Values.frpc.httpPassword | b64enc | quote }}
{{- end }}
